### ISSUE TITLE
Crashes when viewing mods in Mod Menu

### ISSUE THREAD

**Issue by Moe23333** [QuiltMC/quilt-kotlin-libraries#53]
Minecraft Version: 1.18.2
Quilt Version: 0.17.6-beta.2
QKL Version: Snapshot version [1ba1a68](https://github.com/QuiltMC/quilt-kotlin-libraries/commit/1ba1a687861fc990ca0143333d3c75bfcc665a81) in GitHub Actions
Java Version: Eclipse Adoptium JRE 17.0.5 Nightly
Mod Menu version: [Mod Menu v3.2.3 for 1.18.2](https://rewrite.modrinth.com/mod/modmenu/version/3.2.3)

Steps to reproduce the problem:
1. open `Mods` menu in the home page of Minecraft
2. show libraries in the Mod Menu filter
3. scroll down the menu

Log:
```
[11:43:11] [Render thread/ERROR]: Invalid mod icon for icon source qkl_core: assets/qkl/icon.png
java.nio.file.NoSuchFileException: /assets/qkl/icon.png
	at jdk.nio.zipfs.ZipFileSystem.newInputStream(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipPath.newInputStream(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(Unknown Source) ~[jdk.zipfs:?]
	at java.nio.file.Files.newInputStream(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricIconHandler.createIcon(FabricIconHandler.java:34) [modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricDummyParentMod.getIcon(FabricDummyParentMod.java:56) [modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:97) [modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:53) [modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ParentEntry.method_25343(ParentEntry.java:35) [modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:227) [modmenu-3.2.3.jar:?]
	at net.minecraft.class_350.method_25394(class_350.java:219) [client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:280) [modmenu-3.2.3.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:877) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.6-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.6-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.6-beta.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
[11:43:11] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:886) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.6-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.6-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.6-beta.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: java.lang.NullPointerException: Mod icon for qkl is null somehow (should be filled with default in this case)
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricDummyParentMod.getIcon(FabricDummyParentMod.java:56) ~[modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:97) ~[modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:53) ~[modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ParentEntry.method_25343(ParentEntry.java:35) ~[modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:227) ~[modmenu-3.2.3.jar:?]
	at net.minecraft.class_350.method_25394(class_350.java:219) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:280) ~[modmenu-3.2.3.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:877) ~[client-intermediary.jar:?]
	... 16 more
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 10/27/22, 11:43 AM
Description: Rendering screen

java.lang.NullPointerException: Mod icon for qkl is null somehow (should be filled with default in this case)
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at com.terraformersmc.modmenu.util.mod.fabric.FabricDummyParentMod.getIcon(FabricDummyParentMod.java:56)
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:97)
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:53)
	at com.terraformersmc.modmenu.gui.widget.entries.ParentEntry.method_25343(ParentEntry.java:35)
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:227)
	at net.minecraft.class_350.method_25394(class_350.java:219)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:280)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at com.terraformersmc.modmenu.util.mod.fabric.FabricDummyParentMod.getIcon(FabricDummyParentMod.java:56)
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:97)
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:53)
	at com.terraformersmc.modmenu.gui.widget.entries.ParentEntry.method_25343(ParentEntry.java:35)
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:227)
	at net.minecraft.class_350.method_25394(class_350.java:219)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:280)

-- Screen render details --
Details:
	Screen name: com.terraformersmc.modmenu.gui.ModsScreen
	Mouse location: Scaled: (158, 181). Absolute: (317.000000, 363.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2383)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.5-beta, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Eclipse Adoptium
	Memory: 3609778576 bytes (3442 MiB) / 4005560320 bytes (3820 MiB) up to 4188012544 bytes (3994 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x25a9
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2225
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x46a6
	Graphics card #1 versionInfo: DriverVersion=31.0.101.3616
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 6.40
	Memory slot #4 type: Unknown
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 6.40
	Memory slot #5 type: Unknown
	Memory slot #6 capacity (MB): 2048.00
	Memory slot #6 clockSpeed (GHz): 6.40
	Memory slot #6 type: Unknown
	Memory slot #7 capacity (MB): 2048.00
	Memory slot #7 clockSpeed (GHz): 6.40
	Memory slot #7 type: Unknown
	Virtual memory max (MB): 34541.49
	Virtual memory used (MB): 20892.12
	Swap memory total (MB): 18432.00
	Swap memory used (MB): 265.82
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx3993m
	Launched Version: 1.18.2-Quilt 0.17.6-beta.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2050/PCIe/SSE2 GL version 3.2.0 NVIDIA 522.25, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (New Zealand)
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-12500H
```

**Comment by Moe23333** [comment]
Ah... sorry, it maybe because I've used core instead of fatjar, there isn't icon in core but fatjar has.

**Comment by SilverAndro** [comment]
Ah alright then
