### ISSUE TITLE
Cannot play multilplayer with Essential

### ISSUE THREAD

**Issue by Kuggle01** [QuiltMC/quilt-kotlin-libraries#87]
![image](https://github.com/QuiltMC/quilt-kotlin-libraries/assets/77563171/328ee1c0-630a-40f9-a134-999f4cd8d095)
https://mclo.gs/6wkgacf It always brings up this msg whenever we try joining eachothers worlds, we have no idea what is causing it other than it's proably because of kotlin

**Comment by sschr15** [comment]
That is an issue with Essential. If you can disable using QUIC for networking, that may fix the issue.

<details>
<summary>More technical information</summary>

The part of the log discussing this issue is here:
<pre>
[17:39:07] [Server Connector #2/WARN]: Failed to convert "quilt.zfs://org-jetbrains-kotlin-kotlin-stdlib-1.9.10.i0:0/" to file:
java.lang.UnsupportedOperationException: Only the default FileSystem supports 'Path.toFile()', class org.quiltmc.loader.impl.filesystem.QuiltZipPath '/' does not!
	at org.quiltmc.loader.impl.filesystem.QuiltBasePath.toFile(QuiltBasePath.java:580) ~[quilt-loader-0.23.1.jar:?]
	at gg.essential.util.HelpersKt.findCodeSource(helpers.kt:156) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.util.ForkedJvm$Companion.defaultClassPath(ForkedJvm.kt:72) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.sps.quic.jvm.ForkedJvmQuicConnector$Companion.quicConnectorClasspath(ForkedJvmQuicConnector.kt:58) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.sps.quic.jvm.ForkedJvmQuicConnector$Companion.access$quicConnectorClasspath(ForkedJvmQuicConnector.kt:45) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.sps.quic.jvm.ForkedJvmQuicConnector.<init>(ForkedJvmQuicConnector.kt:20) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.sps.quic.jvm.ForkedJvmClientQuicStream.<init>(ForkedJvmClientQuicStream.kt:21) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.network.connectionmanager.ice.IceManager.createClientAgent(IceManager.java:398) ~[Essential (fabric_1.20.1).jar:?]
	at net.minecraft.class_2535.redirect$jnp000$injectLocalChannel(class_2535.java:4088) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_2535.method_52271(class_2535.java:344) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_412$1.run(class_412.java:99) ~[minecraft-1.20.1.i0:0/:?]
[17:39:07] [Server Connector #2/ERROR]: Couldn't connect to server
java.lang.UnsupportedOperationException: Failed to find class kotlin.Unit jar location
	at gg.essential.util.ForkedJvm$Companion.defaultClassPath(ForkedJvm.kt:72) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.sps.quic.jvm.ForkedJvmQuicConnector$Companion.quicConnectorClasspath(ForkedJvmQuicConnector.kt:58) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.sps.quic.jvm.ForkedJvmQuicConnector$Companion.access$quicConnectorClasspath(ForkedJvmQuicConnector.kt:45) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.sps.quic.jvm.ForkedJvmQuicConnector.<init>(ForkedJvmQuicConnector.kt:20) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.sps.quic.jvm.ForkedJvmClientQuicStream.<init>(ForkedJvmClientQuicStream.kt:21) ~[Essential (fabric_1.20.1).jar:?]
	at gg.essential.network.connectionmanager.ice.IceManager.createClientAgent(IceManager.java:398) ~[Essential (fabric_1.20.1).jar:?]
	at net.minecraft.class_2535.redirect$jnp000$injectLocalChannel(class_2535.java:4088) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_2535.method_52271(class_2535.java:344) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_412$1.run(class_412.java:99) ~[minecraft-1.20.1.i0:0/:?]
</pre>

There are a couple main points:
- Essential (trying to use QUIC for secure communications) is attempting to load the `kotlin.Unit` class, a default class in Kotlin's standard libraries. 
- a `Path.toFile()` call works *only* for files in the operating system's default filesystem (e.x. the mods folder, but not the inner data of mods themselves)

The first point there is what leads to the second point. Essential is attempting to find the "default" classpath in order to properly undergo QUIC communications. As a result, it searches through some files.
Below is an approximation of the original code based on a [Vineflower](https://vineflower.org) decompilation of Essential:

```kt
// ForkedJvm.kt
class ForkedJvm {
	// ...
	companion object {
		fun defaultClassPath(): String {
			val sourcePaths = listOf(
				ForkedJvm::class.java,
				Unit::class.java,
				// ...
			).map {
				findCodeSource(it) // declared in Helpers.kt
					?: error("Failed to find class $it jar location") // The message above
			}

			// ...
		}
	}
}
```

This is a relatively simple process, but upon trying to locate the `kotlin.Unit` class (the second call), it fails in `findCodeSource` which propagates the error by returning `null`.

```kt
// Helpers.kt
fun findCodeSource(clazz: Class<*>): CodeSource? {
	var url = clazz.protectionDomain?.codeSource?.location
	// ... Some modifications to the URL. This ends up being a Quilt ZipFS URL eventually.
	// if url ends in .jar, return a Jar code source
	// else:
	try {
		val dir = url // These lines are where the problem occurs. The lines converting the URL into a Path
			.toURI()  // likely are inlined from some other function originating likely from either Kotlin's
			.toPath() // standard libraries or some helper somewhere else in Essential. This ends up causing an
			.toFile() // <-- UnsupportedOperationException
			.toPath() // when Quilt's ZipFS is erroneously given a request to convert to a (native filesystem) File.

		return CodeSource.Directory(dir)
	} catch (e: Exception) {
		LOGGER.warn("Failed to convert \"$url\" to file:", e)
		return null // This is where the null is returned, causing the error to propagate.
	}
}
```

</details>
